# Introduction

In 2020, the COVID19 pandemic transformed our lives and forced us to imagine new ways of working by limiting face to face interactions and contact. Since then, we haven't stopped imagining new ways of communication and transportation. In fact many new services were born. For example, video conferencing tools such as Zoom allowed us to limit face to face interactions by performing meetings online whereas food delivery services allowed us to order food from restaurants that had to close doors due to social distancing rules. Tourism was also strongly impacted due to the effort of containing the virus and limiting its spread. It had a drastic effect on the airline industry since people weren't able to travel for tourism anymore. Business travel were also drastically reduced becausee face-to-face meetings were moved online due to social distancing.

## Todays challenges

In 2023, the amount of flights after the pandemic is back at its pre-pandemic levels. In fact, tourism and business travels are allowed again. However, airlines are facing many new challenges due to other external economical and political factors. The first problem that airlines are facing is the predictability of the demand. In fact due to economical factors such as inflation and increasing costs of goods, customers have more difficulty affording flights. Another challenge that airlines are facing is the unpredictability of supply chain for the repair parts of aircrafts. In fact, COVID 19 started a global problem of shortage of semi-conductors which are very used in modern aviation. The last problem that airlines are facing is the shortage of trained workforce. In fact, because the pandemic forced massive layoffs because of limitations of air traffic, many workers had to reconvert themselves in new professions and now that the demand is back, airlines are struggling filling all the needed jobs to respond to the demand.

## Scope of our work

To draft a solution to these challenges, we are going to analyze daily air traffic data from and to Switzerland in order to predict the amount of flight depending on the weather data in Switzerland and global crude oil prices. By predicting the amount of flights based on seasonality and paterns, airlines should be able to better predict the amount of workers needed and the amount of repair parts needed to maintain the aircrafts.


## What is Brent crude oil and why use it

Brent crude oil is a type of crude oil that is extracted from the North Sea and is one of the major benchmark prices for purchases of oil worldwide. Brent crude oil is light, sweet crude oil that is widely used for production of gasoline and middle distillates. It is named after the Brent goose, which is a common sight in the North Sea. Brent crude oil is traded on the Intercontinental Exchange (ICE) and its price is influenced by a variety of factors, including global supply and demand, geopolitical events, and economic factors.

More specifically, the price of Brent crude oil impacts the price of airplane transportation fuel, as it is one of the main components used in the production of jet fuel. Fluctuations in the price of Brent crude oil can affect the cost of manufacturing jet fuel, which in turn can impact the price of airplane tickets. We assume that if the price of the airplane ticktets is affected, then the demand for flights will also be affected. This is what we are aiming to investigate.